import Head from "next/head";
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from 'react-icons/ai'
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>DB Photography</title>
        <meta name="description" content="Generated by cre"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900"> 
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-white">Daniel Betancourt Photography</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl dark:text-white"/>
              </li>
              <li>
                <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">Daniel Betancourt</h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">Developer and photographer.</h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-slate-200">Freelancer providing services for programming and photography needs!
               Join me down below and let's get cracking!
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={deved} layout="fill" objectFit="cover"/>
          </div>
        </section>

        {/* Second Page */}

        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Services I Offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              Since the beginning of my journey as a Software Developer,
              I have wrote one script that helped streamline important processes
              in the workplace. I wrote the first one in <span className="text-teal-500"> JavaScript </span>
              and am now in the process of writing a more intensive application
              also using <span className="text-teal-500">JavaScript</span> to assist the operations and production team.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              I have worn many hats in the workspace and due to 
              my broad experience I have been very
              fortunate to have developed many valuable skills.
            </p>
          </div>
          <div className="lg:flex gap-10 ">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={design} width={100} height={100} className="mx-auto"/>
              <h3 className="text-lg font-medium pt-8 pb-2 ">Beautiful Designs</h3>
              <p className="py-2">Creating beautiful designs for all of your needs.</p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={code} width={100} height={100} className="mx-auto"/>
              <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Designs</h3>
              <p className="py-2">Creating beautiful designs for all of your needs.</p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={consulting} width={100} height={100} className="mx-auto"/>
              <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Designs</h3>
              <p className="py-2">Creating beautiful designs for all of your needs.</p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              Since the beginning of my journey as a Software Developer,
              I have wrote one script that helped streamline important processes
              in the workplace. I wrote the first one in <span className="text-teal-500"> JavaScript </span>
              and am now in the process of writing a more intensive application
              also using <span className="text-teal-500">JavaScript</span> to assist the operations and production team.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              I have worn many hats in the workspace and due to 
              my broad experience I have been very
              fortunate to have developed many valuable skills.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 flex justify-center">
              <Image 
                src={web1} 
                className="rounded-lg object-cover" 
                width={300} 
                height={200} 
                layout="responsive" 
              />
            </div>
            <div className="basis-1/3 flex-1 flex justify-center">
              <Image 
                src={web2} 
                className="rounded-lg object-cover" 
                width={300} 
                height={200}  
                layout="responsive" 
              />
            </div>
            <div className="basis-1/3 flex-1 flex justify-center">
              <Image 
                src={web3} 
                className="rounded-lg object-cover" 
                width={300} 
                height={200} 
                layout="responsive" 
              />
            </div>
            <div className="basis-1/3 flex-1 flex justify-center">
              <Image 
                src={web4} 
                className="rounded-lg object-cover" 
                width={300} 
                height={200} 
                layout="responsive" 
              />
            </div>
            <div className="basis-1/3 flex-1 flex justify-center">
              <Image 
                src={web5} 
                className="rounded-lg object-cover" 
                width={300} 
                height={200} 
                layout="responsive" 
              />
            </div>
            <div className="basis-1/3 flex-1 flex justify-center">
              <Image 
                src={web6} 
                className="rounded-lg object-cover" 
                width={300} 
                height={200}  
                layout="responsive" 
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
